### ISSUE TITLE
设置Github Pages，同步时却连接Netlify的api

### ISSUE THREAD

**Issue by Tony1026** [EryouHao/gridea-test-install#2]
![QQ图片20211105191451.png](https://i.loli.net/2021/11/05/EIlZeF9vkntyPK3.png)
![QQ图片20211105191742.png](https://i.loli.net/2021/11/05/CbuEHm3dMRABF8G.png)
![QQ图片20211105191508.png](https://i.loli.net/2021/11/05/M79HQ86ayzZKoV1.png)
如图

**Comment by yukino0x** [comment]
你可以下载这个版本的包
![image](https://user-images.githubusercontent.com/59036559/145700621-09e6374b-dc03-473c-94f8-cda0ade748fb.png)

**Comment by Tony1026** [comment]
感谢，之前下过，已经能用了
